Rename various APIs
apple/swift-experimental-string-processing pull request #575
Opened 2022-07-13 21:30 UTC by Azoy

These APIs did not match the proposed spelling, so this changes their names to match what is currently being proposed.

2022-07-13 21:30 UTC, Azoy commented
@swift-ci please test

2022-07-14 13:20 UTC, hamishknight commented on Sources/RegexBuilder/Anchor.swift
>    }
I think you may also have to update the DSL transform for these

2022-07-14 17:30 UTC, milseman requested changes

2022-07-14 18:11 UTC, Azoy commented
@swift-ci please test

2022-07-14 19:18 UTC, milseman approved these changes
LGTM

2022-07-14 22:35 UTC, Azoy commented
@swift-ci please test

2022-07-14 22:56 UTC, merged